version: "3.8"
services:
  bago-music:
    build: .
    ports:
      - "${PORT:-7430}:7430"
    environment:
      - BAGO_TELEGRAM_TOKEN=8519892399:AAHTKzfu_VyLUSpJ-iNjmSn9RcgFOsddeKA
      - PYTHONUNBUFFERED=1
